### ISSUE TITLE
Question about tps

### ISSUE THREAD

**Issue by vonhathanh** [amjltc295/VITON_realtime#3]
Hi @amjltc295, What method did you use to do transform target clothing image to match user body shape.
I guess that you don't use shape context warping like the original paper because the tps folder is missing in your data

**Comment by amjltc295** [comment]
Hi @vonhathanh,

Just as you say, we did not use the TPS transformation since we code not find a Python version to replace the Matlab code. The second stage of the original paper is not implemented, and the result is therefore not as good as the original paper.
What we did is just trimming the cloth and paste it onto the clothes segmentation. It’s just a trick for a better visual result in MakeNTU. It would probably work for T-shirts only but not other complicated clothes.  @nvnnghia says he is working on the second stage though. (See https://github.com/amjltc295/VITON_realtime/issues/1)

Allen

**Comment by vonhathanh** [comment]
@amjltc295  thanks, We are trying to port the TPS code to python, but its hard and we are about to give up :)). So I come here to see if you have another approach to do the virtual try-on without TPS transformation. If we succeed, we'll inform you about our work

**Comment by royaljain** [comment]
> @amjltc295 thanks, We are trying to port the TPS code to python, but its hard and we are about to give up :)). So I come here to see if you have another approach to do the virtual try-on without TPS transformation. If we succeed, we'll inform you about our work

@vonhathanh did you succeed in porting it to python?
