### ISSUE TITLE
An issues about the dataset

### ISSUE THREAD

**Issue by JenniferLiu2017** [amjltc295/VITON_realtime#4]
Hi! The files,"viton_train_images.txt","viton_train_pairs.txt"and"viton_test_pairs.txt" can not be found. I would appreciate it if you could send me these files. My emali is 15610568100@163.com. Looking forward to your early reply.Thank you!

**Comment by amjltc295** [comment]
Hello Jennifer, 

I have uploaded the file you requested. However, please note that according to the original work (https://github.com/xthan/VITON), the dataset has some copyright issues, so it's no longer available. 
These files should be okay since they are just pairs without meaning, but still be careful about using the dataset.

Allen

**Comment by binhmuc** [comment]
Hi, can you give me an example for dataset ?. For example viton_test_pairs.txt has a line "000001_0.jpg 001744_1.jpg"
What is example for 000001_0.jpg  and 001744_1.jpg. I want to know exactly image look like and i wil create data for my self.

**Comment by amjltc295** [comment]
Hi @binhmuc ,

You could  take a look at the VITON paper (https://arxiv.org/pdf/1711.08447.pdf) Figure 1
000001_0.jpg is a model with dress and 000001_1.jpg is the dress that the model is wearing

**Comment by Aashish792** [comment]
HI,
I am Getting issue on

 source activate MakeNTU
bash: activate: No such file or directory

**Comment by Aashish792** [comment]
I am not being able to Download pretrained SS-NAN model could you please upload this in a drive and share its link.
it would be very helpful for me as well a lot of people to see the demo of the program in their own machine
